prgrms-fe-devcourse/FEDC4_HONKOK_JunilHwang

- .prettierrc
- package-lock.json
- package.json
- Prettier Plugin 설치했습니다. 
- close #7
> Prettier Plugin 설치

- .eslintrc.cjs
- package-lock.json
- package.json
ESLint 관련 작업을 진행했습니다.
처음에 적용이 안되어서 삽질을 좀 했네요.. 😥
Vite 관련 기본 설정에서 충돌이 발생해서 안되는 것 같더라구요.
그래서 관련 라이브러리 삭제했습니다.
추가한 eslint가 조금 빡빡하게 잡는 것 같네요.
번거로운 규칙같은 경우는 이야기해보고 없애보죠.
감사합니다..! 🙇‍♂️
- @rushstack/eslint-config 설치
- @typescript-eslint/eslint-plugin 삭제
- close #10
> eslint 관련 작업

- .eslintrc.cjs
- package-lock.json
- package.json
건우님 설정을 보고 잘못 설정된 부분을 파악했네요!
https://github.com/eslint/eslint/issues/3458
이부분 읽어보고 위키에 관련 내용 정리하겠습니다!
- close #20
> eslint 관련 설정

- .eslintrc.cjs
- .storybook/main.ts
- .storybook/preview.ts
- package-lock.json
- package.json
- tailwind.config.js
storybook 설치 및 기본 파일 삭제했습니다!
storybook 설치 시 prettier-plugin-tailwindcss와 충돌이 발생해서
prettier-plugin-tailwindcss 삭제 => storybook install => prettier-plugin-tailwindcss re-install
위와 같은 과정으로 설치를 진행했습니다.
- close #16
> storybook 설치 및 기본 파일 삭제

- .storybook/main.ts
- .storybook/preview.ts
- package-lock.json
- package.json
- src/mocks/components/MyComponent.stories.tsx
- src/mocks/components/MyComponent.tsx
@storybook/addon-styling 설치
mocks 폴더 및 예제 컴포넌트 추가
스토리북 스타일 관련 플러그인 및 예제 컴포넌트 추가했습니다.
관련 문서는 오늘 내로 작성하겠습니다.
- close #26
> 예제 스토리북 추가

- src/components/Button/Button.stories.tsx
- src/components/Button/Button.tsx
- tailwind.config.js
- 버튼 컴포넌트를 storybook에 등록했습니다. (추후 디자인 반영하여 변경할 예정) 
- 색상 팔레트를 임시로 만들어 보았습니다. 
Button 컴포넌트에서 buttonClasses 부분을 어떻게 깔끔하게 할 수 있을지 그리고 맞게 사용했는지 궁금합니다. 
이 또한 디자인이 픽스되면 다시 얘기해 봐야 할 것 같긴합니다.
> 버튼 컴포넌트 생성 및 팔레트 세팅

- src/components/Input/Input.stories.tsx
- src/components/Input/Input.tsx
Input 컴포넌트 관련 작업
Input 컴포넌트 생성
Input story 생성
> Input 컴포넌트 생성

- package-lock.json
- package.json
`dayjs` 라이브러리를 추가하고 Wiki에 설명을 작성했습니다.
[Wiki](https://github.com/prgrms-fe-devcourse/FEDC4_HONKOK_JunilHwang/wiki/%EA%B8%B0%EC%88%A0-%EC%8A%A4%ED%83%9D#-dayjs)에 `dayjs` 추가했습니다. 저희 프로젝트에 사용하는 포맷 키워드는 추후 또 추가하도록 하겠습니다.
- close #53
> dayjs 라이브러리 추가

- .eslintrc.cjs
- src/components/Cards/Card.stories.tsx
- src/components/Image/Image.tsx
- src/hooks/useAuth.ts
- src/hooks/useUser.ts
- src/hooks/userStorage.ts
- src/pages/HomePage.tsx
eslint 규칙을 추가했습니다.
내용은 관련 이슈에서 확인하실 수 있고 다음 코드로 테스트해보시면 됩니다.
```ts
function foo() {
bar();
return;
}
```
삼항연산자 관련해서 `a ? b() : c()` 이거는 자주 쓰일 것 같아 규칙을 변경했습니다.
```
'no-unused-expressions': ['error', { allowTernary: true }]
```
`useUser`에서 해당 부분에는 로직을 변경하거나 규칙을 제거하는 방향으로 이루어져야 할 것 같습니다.
작업하실 때 참고하시길 바랍니다.
```tsx
const { data: user } = useQuery({
queryKey: ['user'],
queryFn: (): any => getUser(user),
initialData: getStoredUser(),
onSuccess: (received) => {
received ? setStoredUser(received) : clearStoredUser();
}
});
```
- close #74
> Eslint 규칙 추가 작업

- src/pages/SignupPage.tsx
- src/routes/Layout.tsx
회원가입 페이지 디자인 작업 진행했습니다.
input에서 border랑 placeholder 색상은 gray-200으로 focus:ouline 색상은 main-base로 우선 사용하겠습니다..!
[피그마 댓글](https://www.figma.com/file/UwTcaHzUGSEhkQone1vWnQ?node-id=445:1468&mode=dev#554239457)
`rem`을 써보는데 상당히 귀찮은 것 같군요..
- close #88
> 회원가입 페이지 디자인 작업

- src/types/model.ts
api response에 쓰이는 타입들을 정리했습니다.
반환 값 사용시 사용되는 타입을 보고 골라서 사용하시면 될 것 같습니다.
프로그래머스의 api 반환 타입을 꼭 확인하고 사용하세요!
- Notification type은 아직 수정 전 입니다.
- close #103
> api types 추가

- src/components/Buttons/Button.tsx
버튼 컴포넌트 기본 스타일에서 텍스트 스타일 제거 했습니다. 
- close #99
이전 커밋도 같이 올라가 버리네요...
> 버튼 컴포넌트 스타일 변경

- src/hooks/useInfiniteScroll.ts
기존의 InfiniteScroll 컴포넌트를 useInfiniteScroll 훅으로 대체합니다.
> 무한 스크롤 리팩토링 

- src/components/Buttons/Button.stories.tsx
버튼 컴포넌트 스토리북 수정 render 부분 추가합니다.
- close #105
> 버튼 컴포넌트 스토리북 수정 

- src/pages/HomePage/HomePage.tsx
- tailwind.config.js
스크롤바를 제거하는 작업을 진행했습니다.
관련해서 위키에 내용을 정리했습니다.
[tailwind에서 스크롤바 없애기](https://github.com/prgrms-fe-devcourse/FEDC4_HONKOK_JunilHwang/wiki/%ED%8A%B8%EB%9F%AC%EB%B8%94-%EC%8A%88%ED%8C%85#tailwind%EC%97%90%EC%84%9C-%EC%8A%A4%ED%81%AC%EB%A1%A4%EB%B0%94-%EC%97%86%EC%95%A0%EA%B8%B0)
위키를 참고해주세요!
- close #122
> 스크롤바 제거 작업

- src/pages/SignupPage.tsx
회원가입 페이지에서 닉네임을 받는 부분을 수정했습니다.
일단 회원가입 기능도 연결 시켰는데 비밀번호 확인하는 부분도 만들어야겠네요..!
비밀번호 확인하는 부분도 이슈를 따로 만들어서 진행하는게 낫겠죠?
- close #111
> 회원가입 페이지 수정

- src/services/notificationService.ts
Header에 알림 개수를 받아오기 위해 api를 제작했습니다.
테스트를 해보려면 토큰 값을 아래에 있는 값으로 넣으면 됩니다. follow에 대한 알림만 생성해 놓은 상태입니다. 
```
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY0Zjg3ZDBiMzZmNGYzMTEwYTYzNTA3OCIsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSJ9LCJpYXQiOjE2OTUwNDQ1MzZ9.MkdMmLk9HCg9QXQZV91Qzsn4Olvg3rdaHCDm0EyUSD4
```
- close #143
> Notification 목록 받아오기 api 관련 작업

- src/services/notificationService.ts
> chore: 함수 반환 타입 지정

- src/components/common/Modal/LoginForm.tsx
- src/components/common/Modal/Modal.tsx
로그인 모달창 스타일 적용했습니다. 
https://github.com/prgrms-fe-devcourse/FEDC4_HONKOK_JunilHwang/assets/99384699/5291cd42-8e08-4368-ad9d-1d9232717f44
건우님 필요하시면 스타일 마음껏 변경하셔도 됩니다!
loginForm을 만들어서 진행했고 modal 디렉토리에 우선 같이 두기는 했는데 어디에 두어야 할지 애매합니다. 
- close
> 로그인 모달창 스타일 적용

- src/components/common/HorizontalScroll/HorizontalScroll.stories.tsx
- src/components/domain/Header/Header.stories.tsx
스토리북 네이밍 관련 작업을 진행했습니다.
- Common으로 변경
- Header 경로 변경
- close #159
> 스토리북 네이밍 작업

- vercel.json
vercel 라우팅 관련 설정을 했습니다.
굳이 이슈를 만들어서 한 이유는, 혹시 수정사항이 있을까 싶었습니다!
`vercel.json` 파일
```json
{
"rewrites": [{ "source": "/(.*)", "destination": "/" }]
}
```
- close #169
> vercel 라우팅 관련 설정

- src/pages/ChatPage/ChatPage.tsx
- src/pages/ConversationPage/ConversationPage.tsx
- src/routes/router.tsx
- src/services/userService.ts
메시지 관련 디자인 작업을 진행했습니다.
**메시지함 페이지**
https://github.com/prgrms-fe-devcourse/FEDC4_HONKOK_JunilHwang/assets/79239852/edd279fb-c462-4c79-9d0c-1b2f5ed230d4
**채팅 페이지**
https://github.com/prgrms-fe-devcourse/FEDC4_HONKOK_JunilHwang/assets/79239852/52ed6b78-9167-47f3-821f-298d19801ebf
채팅 페이지에서 밑에 인풋 스타일은 푸터 스타일 코드를 기반으로 했습니다.
우선 모바일 환경까지는 신경쓰지 못했네요..
- close #201
> 메시지 관련 디자인 작업

- src/components/common/Avatar/Avatar.tsx
- src/pages/FollowPage/FollowPage.tsx
- src/pages/FollowPage/UserList.tsx
- src/pages/ProfileEditPage/components/ProfileEditLabel.tsx
- src/pages/ProfilePage/ProfileHeader.tsx
- src/pages/ProfilePage/ProfilePage.tsx
- src/services/userService.ts
> ProfilePage 리팩토링

- src/components/common/Input/Input.tsx
- src/pages/PostCreatePage/PostCreatePage.tsx
게시글 작성 페이지 피그마 디자인에 맞게 재수정합니다. 
- close
> 게시글 작성 페이지 스타일 수정

- src/pages/PostCreatePage/PostCreatePage.tsx
- src/pages/PostEditPage/PostEditPage.tsx
- 수정 페이지 디자인을 피그마 디자인에 맞게 수정합니다. 
- 글 작성 페이지 디자인을 피그마 디자인에 맞게 수정합니다. 
- close #252
> 수정 페이지 디자인 수정

- src/pages/PostCreatePage/PostCreatePage.tsx
- src/pages/PostCreatePage/components/ChannelList.tsx
- src/pages/PostEditPage/PostEditPage.tsx
- src/utils/validations.ts
글 작성 페이지, 수정 페이지 최적화 작업을 진행했습니다.
onBlur를 통해서 validation검사를 진행하게되었습니다.
글 작성과 글 수정을 진행할 때 제목 바깥 부분을 한번 클릭해야 글 등록 버튼이 활성화 됩니다!
```tsx
const handleTitleBlur = (event: React.FocusEvent<HTMLInputElement>) => {
const title = event.currentTarget.value;
setButtonDisabled(!isValidCreatePost({ title, channelId }));
};
```
> 글 작성 페이지 최적화 작업

- src/components/common/Badge/Badge.tsx
- src/components/common/Modal/Modal.tsx
- src/components/domain/Footer/Footer.tsx
- src/components/domain/Header/Header.tsx
- src/pages/ChannelPage/ChannelPage.tsx
- src/pages/ChatPage/ChatPage.tsx
- src/pages/ConversationPage/ConversationPage.tsx
- src/pages/FollowPage/FollowPage.tsx
- src/pages/HomePage/HomePage.tsx
- src/pages/HomePage/components/ChannelInfo.tsx
- src/pages/LikeListPage/LikeListPage.tsx
- src/pages/NotificationsPage/NotificationsPage.tsx
- src/pages/PostCreatePage/PostCreatePage.tsx
- src/pages/PostEditPage/PostEditPage.tsx
- src/pages/PostPage/PostPage.tsx
- src/pages/PostPage/components/PostContent.tsx
- src/pages/PostPage/components/PostInfo.tsx
- src/pages/PostPage/components/PostLike.tsx
- src/pages/ProfileEditPage/ProfileEditPage.tsx
- src/pages/ProfileEditPage/components/ProfileEditLabel.tsx
- src/pages/ProfilePage/ProfilePage.tsx
- src/pages/SearchPage/SearchPage.tsx
- src/pages/SignUpPage/SignUpPage.tsx
- src/routes/Layout.tsx
- src/routes/LayoutWithFooter.tsx
> hotfix: 스타일 작업

- src/pages/PostCreatePage/PostCreatePage.tsx
- src/pages/PostEditPage/PostEditPage.tsx
글 작성, 수정 시 등록 문제 해결을 진행했습니다.
중복 등록을 방지하고, 글 작성시 등록이 되지 않던 문제를 해결했습니다.
- close #286
> 글 작성, 수정 시 등록 문제 해결

- README.md
react query를 사용한 로그인 상태 해결하기에 대한 설명을 wiki의 기술스택에서 트러블슈팅으로 옮기고 링크를 추가했습니다.
주요 기능은 내일 오전까지 추가할게용!!
> 트러블슈팅 내용 추가
